bind 127.0.0.1
protected-mode yes
port 6379
tcp-backlog 511
timeout 0
tcp-keepalive 300
supervised no
daemonize no
loglevel notice
databases 4
save 900 1
save 300 10
save 60 10000
appendonly yes
appendfsync everysec
