from __future__ import annotations

from enum import Enum


class SecretState(str, Enum):
    MISSING = "MISSING"
    PRESENT = "PRESENT"
    INVALID = "INVALID"


REQUIRED_DATABASE_SECRETS = (
    "POSTGRES_PASSWORD",
    "JWT_SECRET",
    "ANON_KEY",
    "SERVICE_ROLE_KEY",
    "DASHBOARD_USERNAME",
    "DASHBOARD_PASSWORD",
    "SECRET_KEY_BASE",
    "REALTIME_DB_ENC_KEY",
    "VAULT_ENC_KEY",
    "PG_META_CRYPTO_KEY",
    "LOGFLARE_PUBLIC_ACCESS_TOKEN",
    "LOGFLARE_PRIVATE_ACCESS_TOKEN",
    "S3_PROTOCOL_ACCESS_KEY_ID",
    "S3_PROTOCOL_ACCESS_KEY_SECRET",
    "MINIO_ROOT_PASSWORD",
    "SUPABASE_PUBLISHABLE_KEY",
    "SUPABASE_SECRET_KEY",
    "JWT_KEYS",
    "JWT_JWKS",
)

UPSTREAM_GENERATED_SECRETS = {
    "POSTGRES_PASSWORD",
    "JWT_SECRET",
    "ANON_KEY",
    "SERVICE_ROLE_KEY",
    "DASHBOARD_PASSWORD",
    "SECRET_KEY_BASE",
    "REALTIME_DB_ENC_KEY",
    "VAULT_ENC_KEY",
    "PG_META_CRYPTO_KEY",
    "LOGFLARE_PUBLIC_ACCESS_TOKEN",
    "LOGFLARE_PRIVATE_ACCESS_TOKEN",
    "S3_PROTOCOL_ACCESS_KEY_ID",
    "S3_PROTOCOL_ACCESS_KEY_SECRET",
    "MINIO_ROOT_PASSWORD",
    "SUPABASE_PUBLISHABLE_KEY",
    "SUPABASE_SECRET_KEY",
    "JWT_KEYS",
    "JWT_JWKS",
}
