from __future__ import annotations

from typing import Callable, Protocol


class SecretProvider(Protocol):
    def exists(self, key: str) -> bool: ...
    def get(self, key: str) -> str: ...
    def set(self, key: str, value: str) -> None: ...
    def ensure(self, key: str, generator: Callable[[], str]) -> str: ...
