import { Calendar, Plus, CreditCard as Edit2, Trash2, CalendarDays, CalendarRange, CalendarClock, CalendarCheck, List, Hop as Home, ChevronRight, ChevronLeft, TextAlignJustify as AlignJustify, RefreshCw, Search, PanelRight, Copy, ExternalLink, Repeat, Eye, Globe, Star, Share2, FileText, Image as ImageIcon, MapPin, Phone, Users, Bell, Video, ClipboardList } from 'lucide-react';
import type { GuideSection } from './types';

export const CalendarSection: GuideSection = {
  id: 'calendar',
  title: 'تقویم',
  icon: Calendar,
  color: 'teal',
  gradient: 'from-teal-500 to-teal-700',
  overview: 'تقویم شمسی هوشمند با نمای روز، هفته، ماه و لیست — ایجاد، ویرایش و جابجایی رویدادها با Drag & Drop، اشتراک‌گذاری تقویم بین کاربران و نمایش جلسات تایید‌شده.',
  icons: [
    { icon: Plus, name: 'رویداد جدید', desc: 'کلیک روی هر خانه خالی یا دکمه «+» — فرم سریع باز می‌شود', color: 'text-green-600' },
    { icon: Edit2, name: 'ویرایش رویداد', desc: 'آیکن مداد هنگام hover روی رویداد — تغییر زمان، مکان یا رنگ', color: 'text-amber-600' },
    { icon: Trash2, name: 'حذف رویداد', desc: 'حذف رویداد از تقویم با تأیید — رویدادهای تکرارشونده چند گزینه دارند', color: 'text-red-600' },
    { icon: CalendarDays, name: 'نمای ماه', desc: 'جدول ماهانه — تا ۲ رویداد هر روز + دکمه «N دیگر» برای بیشتر', color: 'text-teal-600' },
    { icon: CalendarRange, name: 'نمای هفته', desc: 'نمایش ۷ روز با timeline ساعتی — قابل Drag & Drop و Resize', color: 'text-blue-600' },
    { icon: CalendarClock, name: 'نمای روز', desc: 'timeline کامل روز جاری — ایجاد رویداد با کشیدن', color: 'text-sky-600' },
    { icon: List, name: 'نمای لیست', desc: 'فهرست رویدادها به‌ترتیب زمانی — هفتگی یا ماهانه', color: 'text-slate-600' },
    { icon: Home, name: 'امروز', desc: 'بازگشت فوری به روز جاری در هر نما', color: 'text-indigo-600' },
    { icon: ChevronRight, name: 'ناوبری قبل', desc: 'رفتن به روز / هفته / ماه قبل', color: 'text-teal-500' },
    { icon: ChevronLeft, name: 'ناوبری بعد', desc: 'رفتن به روز / هفته / ماه بعد', color: 'text-teal-500' },
    { icon: Search, name: 'جستجو', desc: 'جستجوی جلسات بر اساس موضوع، مکان یا نماینده', color: 'text-gray-600' },
    { icon: RefreshCw, name: 'بارگذاری مجدد', desc: 'به‌روزرسانی لیست جلسات', color: 'text-slate-500' },
    { icon: AlignJustify, name: 'لیست تقویم‌ها', desc: 'باز کردن modal مدیریت تقویم‌های موجود', color: 'text-purple-600' },
    { icon: Repeat, name: 'رویداد تکرارشونده', desc: 'جلسه‌های ثابت: روزانه، هفتگی یا ماهانه', color: 'text-cyan-600' },
    { icon: Eye, name: 'اشتراک تقویم', desc: 'مشترک شدن در تقویم سایر کاربران سازمان', color: 'text-amber-600' },
    { icon: Globe, name: 'تقویم سازمانی', desc: 'تقویم مشترک عمومی — همه اعضا می‌توانند ببینند', color: 'text-sky-600' },
    { icon: Star, name: 'مناسبت‌های ملی', desc: 'تعطیلات رسمی و مناسبت‌های ملی/مذهبی', color: 'text-yellow-600' },
    { icon: CalendarCheck, name: 'جلسات تایید‌شده', desc: 'جلسات approved به‌صورت خودکار در تقویم نمایش می‌یابند', color: 'text-emerald-600' },
    { icon: Video, name: 'جلسه آنلاین', desc: 'پیوستن به ویدیو کنفرانس مرتبط — ۱۰ دقیقه قبل از شروع', color: 'text-blue-600' },
    { icon: Copy, name: 'کپی لینک مهمان', desc: 'لینک ورود مهمان بدون نیاز به حساب کاربری', color: 'text-teal-600' },
    { icon: PanelRight, name: 'سایدبار موبایل', desc: 'نمایش/پنهان کردن پنل تقویم‌ها در موبایل', color: 'text-gray-500' },
    { icon: Share2, name: 'اشتراک‌گذاری', desc: 'ارسال جزئیات جلسه — تصویر یا متن', color: 'text-green-600' },
    { icon: ExternalLink, name: 'گوگل کلندر', desc: 'انتقال رویداد به Google Calendar', color: 'text-red-600' },
    { icon: MapPin, name: 'مکان', desc: 'محل برگزاری جلسه در preview popup', color: 'text-rose-600' },
    { icon: Users, name: 'شرکت‌کنندگان', desc: 'لیست شرکت‌کنندگان با وضعیت قبول/رد در popup', color: 'text-blue-500' },
    { icon: Bell, name: 'ناظران', desc: 'افرادی که جهت اطلاع در جلسه اضافه شده‌اند', color: 'text-orange-600' },
    { icon: ClipboardList, name: 'دستور جلسه', desc: 'آیتم‌های دستور جلسه در popup جزئیات', color: 'text-slate-600' },
  ],
  steps: [
    {
      title: 'نمای‌های تقویم و ناوبری',
      items: [
        'انتخاب نما از dropdown بالا: ماه، هفته، روز، لیست هفتگی، لیست ماهانه',
        'دکمه «امروز» برای بازگشت سریع به روز جاری',
        'فلش‌های چپ/راست برای ناوبری قبل و بعد',
        'کلیک روی شماره روز در نمای هفته → رفتن به نمای روز',
        'جستجو از نوار بالا برای یافتن جلسه بر اساس موضوع یا مکان',
      ],
    },
    {
      title: 'ایجاد و مدیریت رویداد',
      items: [
        'روی هر خانه خالی کلیک کنید — فرم سریع باز می‌شود',
        'در نمای هفته/روز: بکشید تا رویداد با مدت دلخواه بسازید',
        'رویداد موجود را بکشید (Drag) تا به ساعت یا روز دیگری منتقل شود',
        'لبه پایین رویداد را بکشید تا مدت زمان تنظیم شود',
        'برای رویداد تمام‌روز: در ردیف بالای نمای هفته بکشید',
      ],
    },
    {
      title: 'مدیریت تقویم‌ها',
      items: [
        'آیکن AlignJustify → لیست همه تقویم‌ها باز می‌شود',
        'دکمه «+» در سایدبار → ایجاد تقویم جدید با رنگ دلخواه',
        'تیک هر تقویم را بردارید تا رویدادهایش پنهان شود',
        'برای اشتراک در تقویم کاربر دیگر: آیکن «اشتراک» را بزنید',
        'تقویم سازمانی برای همه اعضا قابل مشاهده است',
      ],
    },
    {
      title: 'Popup جزئیات جلسه',
      items: [
        'کلیک روی هر رویداد → popup جزئیات نمایش می‌یابد',
        'موضوع، زمان، مکان، نماینده و شرکت‌کنندگان نشان داده می‌شوند',
        'دکمه «جزئیات بیشتر» → modal کامل با تمام اطلاعات',
        'دکمه «ویرایش» (اگر مالک باشید) → فرم ویرایش',
        'برای جلسات آنلاین: دکمه پیوستن ۱۰ دقیقه قبل فعال می‌شود',
      ],
    },
  ],
  tips: [
    'در نمای هفته با Drag می‌توانید جلسه را بین روزها جابجا کنید',
    'تقویم مناسبت‌ها به‌صورت خودکار تعطیلات رسمی ایران را نشان می‌دهد',
    'جلسات تایید‌شده به‌طور خودکار در تقویم نمایش می‌یابند بدون نیاز به افزودن دستی',
    'جستجو در تقویم موضوع، مکان و نماینده همه جلسات را جستجو می‌کند',
    'اسپارک می‌تواند تقویم را به تاریخ خاصی ببرد',
  ],
  sparkQuestions: [
    'تقویم امروز را باز کن',
    'برو به نمای ماهانه تقویم',
    'جلسات فردا چیه؟',
    'برو به تاریخ اول مهر',
    'نمای هفتگی را نشان بده',
  ],
};
