import { MessageCircle, Send, Paperclip, Smile, Mic, Reply, Forward, Pin, Tag, Bell, Phone, Video, Trash2, Plus, Star, Search, Info, Copy, CreditCard as Edit2, CircleAlert as AlertCircle, TriangleAlert as AlertTriangle, Lock, ClipboardList, CalendarDays, Bold, AtSign, Eye, MoveVertical as MoreVertical, RefreshCw, MicOff } from 'lucide-react';
import type { GuideSection } from './types';

export const ChatSection: GuideSection = {
  id: 'chat',
  title: 'چت سازمانی',
  icon: MessageCircle,
  color: 'green',
  gradient: 'from-green-500 to-emerald-700',
  overview: 'پیام‌رسان داخلی سازمان — پشتیبانی از متن، صدا، فایل، ویس‌مسج، فرمت‌بندی پیشرفته، پیام‌های اورژانسی/محرمانه، تماس صوتی/تصویری و مدیریت هوشمند وظایف از درون مکالمه.',
  icons: [
    { icon: Plus, name: 'گفتگوی جدید', desc: 'شروع مکالمه با کاربر جدید یا Saved Messages', color: 'text-green-600' },
    { icon: Send, name: 'ارسال پیام', desc: 'ارسال با Enter یا دکمه ارسال', color: 'text-green-600' },
    { icon: Mic, name: 'ویس‌مسج', desc: 'نگه داشتن برای ضبط و رها کردن برای ارسال پیام صوتی', color: 'text-red-600' },
    { icon: MicOff, name: 'لغو ضبط', desc: 'لغو ضبط ویس‌مسج بدون ارسال', color: 'text-gray-500' },
    { icon: Paperclip, name: 'پیوست فایل', desc: 'ارسال فایل، تصویر و اسناد', color: 'text-blue-600' },
    { icon: Smile, name: 'ایموجی', desc: 'افزودن شکلک به متن پیام', color: 'text-yellow-600' },
    { icon: AtSign, name: 'منشن کاربر', desc: 'تایپ @ برای منشن با autocomplete اسامی', color: 'text-purple-600' },
    { icon: Bold, name: 'ویرایشگر پیشرفته', desc: 'فرمت‌بندی: Bold، Italic، Quote، Code، لیست، لینک', color: 'text-slate-600' },
    { icon: AlertCircle, name: 'پیام مهم', desc: 'ارسال با اعلان ویژه در صفحه — با رنگ نارنجی', color: 'text-orange-600' },
    { icon: AlertTriangle, name: 'پیام اورژانسی', desc: 'ارسال با صدای آلارم — برای مواقع فوری', color: 'text-red-600' },
    { icon: Lock, name: 'پیام محرمانه', desc: 'محتوا تا کلیک پنهان است — برای اطلاعات حساس', color: 'text-slate-600' },
    { icon: Reply, name: 'پاسخ', desc: 'پاسخ ارجاع‌دار به پیام خاص — قابل کلیک برای رفتن به پیام اصلی', color: 'text-sky-600' },
    { icon: Forward, name: 'فوروارد', desc: 'ارسال پیام به مکالمه یا کانال دیگر', color: 'text-teal-600' },
    { icon: Edit2, name: 'ویرایش پیام', desc: 'تغییر متن پیام ارسال‌شده — فقط پیام‌های خود', color: 'text-amber-600' },
    { icon: Trash2, name: 'حذف پیام', desc: 'حذف فقط برای من یا حذف برای همه', color: 'text-red-500' },
    { icon: Star, name: 'ستاره‌گذاری', desc: 'ذخیره پیام مهم — قابل مشاهده در پنل ستاره‌ها', color: 'text-yellow-500' },
    { icon: Tag, name: 'برچسب', desc: 'افزودن تگ رنگی به پیام برای دسته‌بندی', color: 'text-purple-600' },
    { icon: Bell, name: 'یادآور پیام', desc: 'تنظیم یادآور: ۳۰ دق، ۱ ساعت، فردا یا زمان دلخواه', color: 'text-orange-600' },
    { icon: ClipboardList, name: 'ثبت به عنوان وظیفه', desc: 'تبدیل پیام به اقدام در کارتابل — با یک کلیک', color: 'text-emerald-600' },
    { icon: Pin, name: 'پین', desc: 'پین خصوصی پیام برای دسترسی سریع شخصی', color: 'text-amber-600' },
    { icon: Copy, name: 'کپی متن', desc: 'کپی متن پیام در کلیپ‌بورد', color: 'text-slate-600' },
    { icon: Eye, name: 'وضعیت خوانده‌شدن', desc: 'مشاهده لیست افرادی که پیام را خوانده‌اند', color: 'text-blue-500' },
    { icon: Search, name: 'جستجو در مکالمه', desc: 'جستجوی متن در تاریخچه پیام‌ها', color: 'text-gray-600' },
    { icon: CalendarDays, name: 'پرش به تاریخ', desc: 'رفتن به تاریخ خاص در تاریخچه مکالمه', color: 'text-teal-600' },
    { icon: Phone, name: 'تماس صوتی', desc: 'شروع تماس صوتی مستقیم با کاربر', color: 'text-green-600' },
    { icon: Video, name: 'تماس تصویری', desc: 'شروع ویدیو کال با کاربر', color: 'text-blue-600' },
    { icon: Info, name: 'پنل اطلاعات', desc: 'نمایش فایل‌ها، تصاویر و اعضای مکالمه', color: 'text-indigo-600' },
    { icon: MoreVertical, name: 'منوی پیام', desc: 'راست‌کلیک یا نگه داشتن — منوی کامل عملیات', color: 'text-slate-500' },
  ],
  steps: [
    {
      title: 'شروع مکالمه',
      items: [
        'آیکن «+» در سایدبار → جستجوی نام کاربر',
        'کلیک روی نام → مکالمه باز می‌شود',
        'تایپ کنید و Enter بزنید یا دکمه ارسال را فشار دهید',
        'برای Saved Messages: روی نام خودتان کلیک کنید',
      ],
    },
    {
      title: 'ارسال انواع پیام',
      items: [
        'پیام معمولی: تایپ کنید و Enter بزنید',
        'ویس‌مسج: دکمه Mic را نگه دارید و رها کنید',
        'پیام مهم: آیکن نوع پیام را روی «مهم» تنظیم کنید',
        'پیام اورژانسی: آیکن نوع پیام → «اورژانسی» — با صدای آلارم ارسال می‌شود',
        'پیام محرمانه: آیکن قفل — محتوا تا کلیک گیرنده پنهان است',
        'فرمت‌بندی: آیکن Bold برای ویرایشگر پیشرفته',
      ],
    },
    {
      title: 'مدیریت پیام‌ها',
      items: [
        'هولد روی پیام یا راست‌کلیک → منوی کامل عملیات',
        'ستاره‌گذاری: ذخیره پیام مهم در پنل ستاره‌ها',
        'یادآور: تنظیم تایمر برای پیام — در پنل یادآورها نمایش می‌یابد',
        'ثبت به عنوان وظیفه: تبدیل پیام به اقدام در کارتابل',
        'وضعیت: ✓ ارسال، ✓✓ تحویل، ✓✓ آبی = خوانده شده',
      ],
    },
  ],
  tips: [
    'پیام اورژانسی صدای آلارم پخش می‌کند — برای موارد واقعاً فوری استفاده کنید',
    'با @ می‌توانید کاربر را منشن کنید — او نوتیفیکیشن جداگانه دریافت می‌کند',
    'پیام‌های ستاره‌دار در پنل «ستاره‌ها» در header مکالمه قابل دسترسی هستند',
    'اسپارک می‌تواند از طرف شما پیام ارسال کند',
    'گفتگوهای حذف‌شده فقط برای شما پاک می‌شوند',
  ],
  sparkQuestions: [
    'پیام بده به زهرا با موضوع پیگیری پروژه',
    'تماس صوتی با علی بگیر',
    'برو به صفحه چت',
  ],
};
