import {
  Bot, Zap, Sparkles, Brain, Mic, Volume2, RefreshCw, VolumeX,
  Send, Trash2, Search, ListFilter as Filter, Play,
  CircleCheck as CheckCircle2, CircleAlert as AlertCircle,
  ChevronDown, ChevronUp, Terminal, BookOpen, Users, Square,
} from 'lucide-react';
import type { GuideSection } from './types';

export const SparkSection: GuideSection = {
  id: 'spark',
  title: 'اسپارک (دستیار هوشمند)',
  icon: Bot,
  color: 'sky',
  gradient: 'from-sky-500 to-blue-600',
  overview: 'دستیار هوشمند فارسی‌زبان با ورودی متن و صدا — دستورات سازمانی را اجرا می‌کند، تاریخچه دستورات را نگه می‌دارد، و از طریق FAB شناور در همه صفحات قابل دسترسی است.',
  icons: [
    { icon: Bot, name: 'FAB اسپارک', desc: 'دکمه شناور در گوشه صفحه — در همه صفحات قابل دسترسی', color: 'text-sky-500' },
    { icon: Send, name: 'ارسال دستور', desc: 'ارسال متن دستور با دکمه ارسال یا Enter', color: 'text-sky-600' },
    { icon: Mic, name: 'ورودی صوتی', desc: 'ضبط دستور با صدا — تبدیل به متن و پردازش', color: 'text-red-600' },
    { icon: Square, name: 'توقف ضبط', desc: 'توقف ضبط صدا', color: 'text-gray-500' },
    { icon: Volume2, name: 'پاسخ صوتی', desc: 'خواندن پاسخ توسط اسپارک — text-to-speech', color: 'text-teal-600' },
    { icon: VolumeX, name: 'بی‌صدا', desc: 'خاموش کردن پاسخ صوتی اسپارک', color: 'text-gray-500' },
    { icon: RefreshCw, name: 'رفرش تنظیمات', desc: 'بارگذاری مجدد تنظیمات و کلید API', color: 'text-slate-600' },
    { icon: CheckCircle2, name: 'تأیید اجرا', desc: 'تأیید دستور شناسایی‌شده: «بله، اجرا کن»', color: 'text-green-600' },
    { icon: AlertCircle, name: 'لغو دستور', desc: 'لغو دستور شناسایی‌شده قبل از اجرا', color: 'text-red-500' },
    { icon: Zap, name: 'AI فعال', desc: 'هوش مصنوعی Groq/OpenAI متصل — پردازش پیشرفته', color: 'text-yellow-500' },
    { icon: Sparkles, name: 'اسپارک پایه', desc: 'پردازش محلی بدون کلید API — برای دستورات ساده', color: 'text-sky-500' },
    { icon: Brain, name: 'حافظه', desc: 'اسپارک مخاطبین و الگوهای پرتکرار را حفظ می‌کند', color: 'text-purple-600' },
    { icon: Terminal, name: 'صفحه دستورات', desc: 'پنل SparkPage: تمپلیت‌های آماده + اجرای دستور دستی', color: 'text-slate-700' },
    { icon: BookOpen, name: 'تمپلیت‌ها', desc: 'دستورات آماده گروه‌بندی‌شده: جلسه، اقدام، یادداشت، پیام', color: 'text-blue-600' },
    { icon: Search, name: 'جستجو لاگ', desc: 'جستجو در تاریخچه دستورات اجراشده', color: 'text-gray-600' },
    { icon: Filter, name: 'فیلتر لاگ', desc: 'فیلتر تاریخچه: همه، موفق، ناموفق', color: 'text-purple-600' },
    { icon: Trash2, name: 'حذف لاگ', desc: 'حذف همه یا حذف تک‌تک لاگ‌ها', color: 'text-red-500' },
    { icon: Play, name: 'اجرای تمپلیت', desc: 'اجرای مستقیم دستور از لیست تمپلیت', color: 'text-green-600' },
    { icon: ChevronDown, name: 'باز کردن پنل', desc: 'باز/بسته کردن پنل ورودی دستور', color: 'text-slate-500' },
    { icon: Users, name: 'دستورات تیمی', desc: 'تمپلیت‌های مرتبط با مدیریت تیم و کاربران', color: 'text-blue-500' },
  ],
  steps: [
    {
      title: 'استفاده از FAB اسپارک',
      items: [
        'روی دکمه شناور Bot در گوشه صفحه کلیک کنید',
        'متن دستور را تایپ کنید یا میکروفون را فشار دهید',
        'اسپارک دستور را شناسایی و برای تأیید می‌پرسد',
        'روی «بله، اجرا کن» کلیک کنید — عملیات انجام می‌شود',
        'FAB قابل کشیدن است — موقعیتش را تغییر دهید',
      ],
    },
    {
      title: 'صفحه دستورات (SparkPage)',
      items: [
        'از منوی اصلی به «اسپارک» بروید',
        'تب «دستورات»: تمپلیت‌های آماده گروه‌بندی‌شده',
        'روی هر تمپلیت کلیک کنید تا در input کپی شود',
        'دکمه Play روی هر تمپلیت — اجرای مستقیم',
        'تب «لاگ‌ها»: تاریخچه کامل دستورات با وضعیت',
        'آمار: کل، موفق، ناموفق، به تفکیک نوع',
      ],
    },
    {
      title: 'دستورات قابل اجرا',
      items: [
        '«جلسه [موضوع] را لغو کن» — لغو جلسه',
        '«جلسه [موضوع] را یک ساعت جلو بنداز» — تغییر زمان',
        '«پیام بده به [نام] با موضوع [متن]» — ارسال پیام',
        '«اقدام ایجاد کن: [عنوان] برای [نام]» — ایجاد وظیفه',
        '«یادداشت ثبت کن: [عنوان]» — ایجاد یادداشت',
        '«مخاطب اضافه کن: [نام] [شماره]» — ثبت مخاطب',
        '«برو به [صفحه]» — ناوبری در برنامه',
        'هر سوال فارسی — اسپارک پاسخ می‌دهد',
      ],
    },
  ],
  tips: [
    'FAB اسپارک در همه صفحات حاضر است — نیازی به رفتن به صفحه خاص نیست',
    'هر دستور فارسی قابل قبول است — کامل یا خلاصه',
    'اگر اطلاعات کامل نباشد اسپارک می‌پرسد — لازم نیست همه چیز را در یک جمله بگویید',
    'لاگ دستورات را در SparkPage ببینید تا از اجرای موفق مطمئن شوید',
    'دستورات صوتی با دکمه Mic در FAB یا SparkPage فعال می‌شوند',
  ],
  sparkQuestions: [
    'چه کارهایی می‌تونی انجام بدی؟',
    'جلسات امروز را لیست کن',
    'نمای ماهانه تقویم را نشان بده',
  ],
};
