import {
  Video, Plus, Mic, MicOff, VideoOff, LayoutGrid, MonitorPlay,
  UserPlus, LogIn, Copy, Send, Search, RefreshCw,
  Globe, Lock, Shield, LogOut, Users, Clock, ChevronRight,
  ScreenShare, ScreenShareOff, Hand, MessageSquare, PenTool,
  ChartBar as BarChart2, SlidersHorizontal, Smile, Crown,
  UserX, ShieldAlert, Pin, Volume2, VolumeX, PhoneOff,
  Maximize2, Activity, PanelRight, ArrowRightLeft,
} from 'lucide-react';
import type { GuideSection } from './types';

export const VideoSection: GuideSection = {
  id: 'video',
  title: 'ویدیو کنفرانس',
  icon: Video,
  color: 'indigo',
  gradient: 'from-sky-500 to-blue-700',
  overview: 'سیستم ویدیو کنفرانس داخلی — ایجاد یا پیوستن به اتاق، کنترل میکروفون/دوربین، اشتراک صفحه، تابلو سفید، نظرسنجی، چت، مدیریت شرکت‌کنندگان و ریکشن‌های ایموجی. بدون نرم‌افزار جانبی — مستقیم در مرورگر.',
  icons: [
    { icon: Plus, name: 'اتاق جدید', desc: 'ایجاد اتاق کنفرانس جدید با نام دلخواه', color: 'text-blue-600' },
    { icon: LogIn, name: 'پیوستن با کد', desc: 'ورود به اتاق موجود با وارد کردن کد اتاق', color: 'text-green-600' },
    { icon: ChevronRight, name: 'ورود سریع', desc: 'دکمه «ورود» روی کارت اتاق در لیست', color: 'text-teal-600' },
    { icon: Mic, name: 'میکروفون روشن', desc: 'ضبط و ارسال صدا — قابل toggle در هر زمان', color: 'text-green-600' },
    { icon: MicOff, name: 'میکروفون خاموش', desc: 'قطع صدا — بدون اطلاع به سایرین', color: 'text-red-600' },
    { icon: Video, name: 'دوربین روشن', desc: 'ارسال تصویر دوربین به اتاق', color: 'text-blue-600' },
    { icon: VideoOff, name: 'دوربین خاموش', desc: 'قطع تصویر — آواتار به جای دوربین نمایش می‌یابد', color: 'text-red-600' },
    { icon: ScreenShare, name: 'اشتراک صفحه', desc: 'اشتراک‌گذاری نمایشگر یا پنجره خاص', color: 'text-purple-600' },
    { icon: ScreenShareOff, name: 'توقف اشتراک', desc: 'متوقف کردن اشتراک صفحه', color: 'text-red-600' },
    { icon: Hand, name: 'بلند کردن دست', desc: 'اعلام درخواست صحبت — در لیست شرکت‌کنندگان نمایش می‌یابد', color: 'text-yellow-600' },
    { icon: Smile, name: 'ریکشن ایموجی', desc: 'ارسال ایموجی واکنش — روی تصویر شرکت‌کنندگان نمایش می‌یابد', color: 'text-yellow-500' },
    { icon: MessageSquare, name: 'چت اتاق', desc: 'پنل پیام‌رسانی درون اتاق — با badge تعداد پیام‌های خوانده‌نشده', color: 'text-sky-600' },
    { icon: Users, name: 'شرکت‌کنندگان', desc: 'پنل مدیریت اعضا — لیست، دست‌های بلند و نقش‌ها', color: 'text-blue-500' },
    { icon: PenTool, name: 'تابلو سفید', desc: 'whiteboard مشترک برای رسم و نوشتن همزمان', color: 'text-teal-600' },
    { icon: BarChart2, name: 'نظرسنجی', desc: 'ایجاد و مشاهده نتایج نظرسنجی زنده', color: 'text-indigo-600' },
    { icon: SlidersHorizontal, name: 'تنظیمات', desc: 'انتخاب دوربین/میکروفون، کیفیت ویدیو و ابزارهای تشخیصی', color: 'text-slate-600' },
    { icon: LayoutGrid, name: 'نمای گالری', desc: 'همه شرکت‌کنندگان با اندازه مساوی در شبکه', color: 'text-teal-600' },
    { icon: MonitorPlay, name: 'نمای اسپیکر', desc: 'بزرگ‌نمایی خودکار گوینده فعال — مناسب ارائه', color: 'text-purple-600' },
    { icon: PanelRight, name: 'نمای سایدبار', desc: 'ویدیوی اصلی + نوار کناری شرکت‌کنندگان', color: 'text-slate-600' },
    { icon: Maximize2, name: 'تمام‌صفحه', desc: 'ورود/خروج از حالت تمام‌صفحه', color: 'text-gray-600' },
    { icon: Volume2, name: 'صدای بلندگو', desc: 'کنترل بلندگو — قابل قطع و وصل', color: 'text-green-600' },
    { icon: VolumeX, name: 'بی‌صدا کردن بلندگو', desc: 'قطع صدای تمام شرکت‌کنندگان برای خود', color: 'text-red-600' },
    { icon: Crown, name: 'انتقال میزبانی', desc: 'واگذاری نقش میزبان به شرکت‌کننده دیگر', color: 'text-yellow-600' },
    { icon: Pin, name: 'پین شرکت‌کننده', desc: 'ثابت نگه داشتن ویدیوی یک شرکت‌کننده در صفحه', color: 'text-amber-600' },
    { icon: ArrowRightLeft, name: 'تغییر نقش', desc: 'تغییر سطح دسترسی شرکت‌کننده توسط میزبان', color: 'text-violet-600' },
    { icon: UserX, name: 'اخراج', desc: 'حذف شرکت‌کننده از اتاق — فقط میزبان', color: 'text-red-600' },
    { icon: ShieldAlert, name: 'مسدودسازی', desc: 'Ban شرکت‌کننده با مدت‌زمان — ۱۵ دقیقه، ۱ ساعت یا دائمی', color: 'text-red-700' },
    { icon: UserPlus, name: 'دعوت اعضا', desc: 'جستجو و ارسال دعوت‌نامه به کاربران سازمان', color: 'text-teal-600' },
    { icon: Copy, name: 'کپی کد اتاق', desc: 'کپی کد کوتاه برای اشتراک‌گذاری', color: 'text-slate-600' },
    { icon: Globe, name: 'لینک عمومی', desc: 'لینک کامل ورود — قابل کپی و ارسال', color: 'text-green-600' },
    { icon: Lock, name: 'اتاق قفل', desc: 'اتاقی که ورود جدید ممنوع است', color: 'text-red-600' },
    { icon: Shield, name: 'تأیید میزبان', desc: 'فعال کردن اتاق انتظار — ورود نیاز به تأیید دارد', color: 'text-amber-600' },
    { icon: Activity, name: 'وضعیت ضبط', desc: 'نشانگر فعال بودن ضبط جلسه (در صورت فعال)', color: 'text-rose-600' },
    { icon: Clock, name: 'مدت جلسه', desc: 'تایمر نمایش مدت زمان جلسه', color: 'text-teal-600' },
    { icon: Search, name: 'جستجو برای دعوت', desc: 'جستجوی کاربران سازمان برای ارسال دعوت', color: 'text-gray-600' },
    { icon: Send, name: 'ارسال دعوت', desc: 'ارسال نوتیفیکیشن دعوت به کاربران انتخاب‌شده', color: 'text-sky-600' },
    { icon: RefreshCw, name: 'بارگذاری مجدد', desc: 'به‌روزرسانی لیست اتاق‌های فعال', color: 'text-slate-500' },
    { icon: LogOut, name: 'خروج', desc: 'خروج از اتاق — جلسه برای سایرین ادامه می‌یابد', color: 'text-amber-600' },
    { icon: PhoneOff, name: 'پایان / خروج', desc: 'دکمه قطع — خروج یا پایان کامل جلسه برای همه (میزبان)', color: 'text-red-600' },
  ],
  steps: [
    {
      title: 'برگزاری جلسه جدید',
      items: [
        'روی «اتاق جدید» کلیک کنید و نام اتاق را وارد کنید',
        'تنظیمات قبل از ورود: میکروفون و دوربین را چک کنید',
        'در صورت نیاز «تأیید میزبان» را فعال کنید تا اتاق انتظار داشته باشد',
        'روی «ورود» کلیک کنید — اتاق فعال می‌شود',
        'کد اتاق یا لینک را کپی کنید و برای دیگران ارسال کنید',
        'با آیکن دعوت، کاربران سازمان را دعوت کنید',
      ],
    },
    {
      title: 'پیوستن به اتاق',
      items: [
        'در لیست اتاق‌های فعال روی «ورود» کلیک کنید',
        'یا «پیوستن با کد» → کد اتاق را وارد کنید',
        'اگر اتاق انتظار دارد: منتظر تأیید میزبان بمانید',
        'اگر ممنوعیت (Ban) دارید، پیام دلیل نمایش می‌یابد',
      ],
    },
    {
      title: 'کنترل‌های درون اتاق',
      items: [
        'Mic و Camera در نوار پایین قابل toggle هستند',
        'اشتراک صفحه: آیکن ScreenShare — نمایشگر یا پنجره خاص',
        'نمای گالری، اسپیکر یا سایدبار از دکمه‌های بالا انتخاب کنید',
        'پنل‌های چت، اعضا، تابلو سفید، نظرسنجی و تنظیمات از نوار پایین',
        'برای خروج: دکمه قرمز PhoneOff — میزبان می‌تواند اتاق را برای همه ببندد',
      ],
    },
    {
      title: 'مدیریت شرکت‌کنندگان (میزبان)',
      items: [
        'پنل «اعضا» را باز کنید — لیست همه شرکت‌کنندگان',
        'دست‌های بلند با رنگ زرد مشخص می‌شوند',
        'روی هر شرکت‌کننده: قطع صدا، تغییر نقش، انتقال میزبانی، اخراج یا Ban',
        'Ban با مدت‌زمان: ۱۵ دقیقه، ۱ ساعت یا دائمی',
        '«قطع صدای همه» در پنل اعضا — یکجا همه را بی‌صدا کنید',
      ],
    },
  ],
  tips: [
    'کد اتاق را کپی کنید — کاربران خارج از سازمان هم با لینک می‌توانند وارد شوند',
    'اتاق انتظار (Shield) برای کنترل ورود مهمانان مفید است',
    'ریکشن‌های ایموجی روی ویدیوی هر شرکت‌کننده به صورت شناور نمایش می‌یابند',
    'تابلو سفید (Whiteboard) برای همه اعضا به‌صورت همزمان قابل استفاده است',
    'لیست اتاق‌های فعال به‌صورت real-time به‌روز می‌شود',
  ],
  sparkQuestions: [
    'برو به صفحه ویدیو کنفرانس',
    'تماس تصویری با علی بگیر',
  ],
};
