import {
  FileText,
  Users,
  SquareCheck as CheckSquare,
  Paperclip,
  Shield,
  Signature as FileSignature,
} from 'lucide-react';

export const MINUTES_FORM_SECTIONS = [
  { id: 'info', label: 'اطلاعات جلسه', icon: FileText },
  { id: 'participants', label: 'شرکت‌کنندگان', icon: Users },
  { id: 'agenda', label: 'دستور جلسات', icon: CheckSquare },
  { id: 'decisions', label: 'مصوبات', icon: CheckSquare },
  { id: 'attachments', label: 'پیوست‌ها', icon: Paperclip },
  { id: 'approvers', label: 'تأییدکنندگان', icon: Shield },
  { id: 'final', label: 'نسخه نهایی', icon: FileSignature },
] as const;

export const MINUTES_RPC_ERROR_MESSAGES: Record<string, string> = {
  NOT_AUTHENTICATED: 'احراز هویت نشده‌اید. لطفاً دوباره وارد شوید.',
  PAYLOAD_INVALID: 'اطلاعات ارسالی نامعتبر است.',
  MEETING_ID_REQUIRED: 'انتخاب جلسه الزامی است.',
  TITLE_REQUIRED: 'عنوان جلسه الزامی است.',
  DATE_REQUIRED: 'تاریخ جلسه الزامی است.',
  SECRETARY_NAME_REQUIRED: 'نام دبیر جلسه الزامی است.',
  CHAIR_NAME_REQUIRED: 'نام رئیس جلسه الزامی است.',
  INVALID_CONFIDENTIALITY: 'سطح محرمانگی نامعتبر است.',
  MEETING_NO_PERMISSION: 'شما اجازه ایجاد صورت‌جلسه برای این جلسه را ندارید.',
  MINUTES_ALREADY_EXISTS: 'برای این جلسه قبلاً صورت‌جلسه ثبت شده است.',
  SECRETARY_USER_NOT_FOUND: 'کاربر دبیر جلسه یافت نشد.',
  CHAIR_USER_NOT_FOUND: 'کاربر رئیس جلسه یافت نشد.',
  ORG_UNIT_NOT_FOUND: 'واحد سازمانی یافت نشد.',
  PARTICIPANT_NAME_REQUIRED: 'نام شرکت‌کننده الزامی است.',
  PARTICIPANT_USER_NOT_FOUND: 'کاربر شرکت‌کننده یافت نشد.',
  INVALID_INVITATION_STATUS: 'وضعیت دعوت نامعتبر است.',
  INVALID_ATTENDANCE_STATUS: 'وضعیت حضور نامعتبر است.',
  EXTERNAL_NAME_REQUIRED: 'نام شرکت‌کننده خارجی الزامی است.',
  EXTERNAL_PARTICIPANT_NAME_REQUIRED: 'نام شرکت‌کننده خارجی الزامی است.',
  AGENDA_TITLE_REQUIRED: 'عنوان دستور جلسه الزامی است.',
  AGENDA_SORT_ORDER_INVALID: 'ترتیب دستور جلسه نامعتبر است.',
  AGENDA_ALLOCATED_TIME_INVALID: 'زمان اختصاص‌یافته دستور جلسه نامعتبر است.',
  INVALID_RESULT_TYPE: 'نوع نتیجه دستور جلسه نامعتبر است.',
  AGENDA_ITEM_MISMATCH: 'مغایرت در دستور جلسات.',
  DUPLICATE_INTERNAL_PARTICIPANT: 'شرکت‌کننده داخلی تکراری است.',
  DUPLICATE_AGENDA_ITEM: 'دستور جلسه تکراری است.',
  INVALID_APPROVAL_MODE: 'مدل تأیید نامعتبر است.',
  SECRETARY_NOT_MEETING_PARTICIPANT: 'دبیر جلسه باید از شرکت‌کنندگان جلسه باشد.',
  CHAIR_NOT_MEETING_PARTICIPANT: 'رئیس جلسه باید از شرکت‌کنندگان جلسه باشد.',
  DECISION_TITLE_REQUIRED: 'عنوان مصوبه الزامی است.',
  DECISION_OWNER_REQUIRED: 'مسئول مصوبه الزامی است.',
  DECISION_DUE_BEFORE_START: 'مهلت مصوبه نمی‌تواند قبل از تاریخ شروع باشد.',
  MINUTES_NO_PERMISSION: 'شما اجازه انجام این عملیات را ندارید.',
  MINUTES_VERSION_CONFLICT: 'این صورت‌جلسه توسط کاربر دیگری تغییر کرده است. اطلاعات را دوباره بارگذاری کنید.',
  MINUTE_NOT_FOUND: 'صورت‌جلسه یافت نشد.',
  NO_ELIGIBLE_APPROVERS: 'هیچ شرکت‌کننده واجد شرایطی برای تأیید سیستمی وجود ندارد.',
  MINUTE_NOT_SUBMITTABLE: 'این صورت‌جلسه در وضعیت قابل ارسال نیست.',
  APPROVAL_MODE_IMMUTABLE: 'مدل تأیید پس از اولین ارسال قابل تغییر نیست.',
  INTERNAL_ERROR: 'خطای داخلی سرور رخ داد. لطفاً دوباره تلاش کنید.',
  MINUTES_NOT_PUBLISHED: 'این مصوبه تا زمان انتشار صورت‌جلسه قابل مشاهده یا پیگیری نیست.',
  INVALID_EXTERNAL_PARTICIPANT_ID: 'شناسه شرکت‌کننده خارج سازمان نامعتبر است. صفحه را تازه‌سازی و دوباره تلاش کنید.',
};

export const MINUTES_SUBMIT_ERROR_MESSAGES: Record<string, string> = {
  NOT_AUTHENTICATED: 'برای ارسال باید وارد شده باشید.',
  MINUTE_NOT_FOUND: 'صورت‌جلسه یافت نشد.',
  MINUTES_NO_PERMISSION: 'شما اجازه ارسال این صورت‌جلسه را ندارید.',
  MINUTE_NOT_SUBMITTABLE: 'این صورت‌جلسه در وضعیت قابل ارسال نیست.',
  MINUTES_VERSION_CONFLICT: 'این صورت‌جلسه توسط کاربر دیگری تغییر کرده است. اطلاعات را دوباره بارگذاری کنید.',
  APPROVAL_MODE_IMMUTABLE: 'مدل تأیید پس از اولین ارسال قابل تغییر نیست.',
  INVALID_APPROVAL_MODE: 'مدل تأیید نامعتبر است.',
  NO_ELIGIBLE_APPROVERS: 'هیچ شرکت‌کننده واجد شرایطی برای تأیید سیستمی وجود ندارد.',
  MINUTES_NOT_PUBLISHED: 'این مصوبه تا زمان انتشار صورت‌جلسه قابل مشاهده یا پیگیری نیست.',
};
