// Temporary mock data — replace with real data integration in later phase.
// NOTE: MOCK_DECISIONS is still referenced by MinutesDashboardPage and
// MinutesMeetingReportPage (out of scope for the decisions wiring task).
// The in-scope pages (Form/Detail/MyDecisions/Followup) no longer use it.

import type {
  MinuteSummary,
  ApprovalSummary,
  InternalParticipant,
  ExternalParticipant,
  AgendaItem,
  HistoryEvent,
  DecisionSummary,
} from './types';

export const MOCK_MINUTES: MinuteSummary[] = [
  {
    id: 'm1',
    meetingTitle: 'جلسه بررسی برنامه‌ریزی سالانه',
    meetingDate: '۱۴۰۳/۰۵/۱۲',
    secretary: 'علی محمدی',
    chair: 'دکتر حسینی',
    status: 'published',
    confidentiality: 'organizational',
    decisionCount: 5,
    lastModified: '۱۴۰۳/۰۵/۱۵',
    version: '۱.۲',
    orgUnit: 'معاونت برنامه‌ریزی',
  },
  {
    id: 'm2',
    meetingTitle: 'جلسه هماهنگی پروژه سامانه مدیریت',
    meetingDate: '۱۴۰۳/۰۵/۰۸',
    secretary: 'سارا کریمی',
    chair: 'مهندس رضایی',
    status: 'approved',
    confidentiality: 'restricted',
    decisionCount: 3,
    lastModified: '۱۴۰۳/۰۵/۱۰',
    version: '۱.۰',
    orgUnit: 'اداره فناوری اطلاعات',
  },
  {
    id: 'm3',
    meetingTitle: 'جلسه بررسی بودجه نیمه دوم سال',
    meetingDate: '۱۴۰۳/۰۵/۰۳',
    secretary: 'محمد احمدی',
    chair: 'مدیرعامل',
    status: 'pending_approval',
    confidentiality: 'confidential',
    decisionCount: 7,
    lastModified: '۱۴۰۳/۰۵/۰۵',
    version: '۰.۸',
    orgUnit: 'اداره مالی',
  },
  {
    id: 'm4',
    meetingTitle: 'جلسه ارزیابی عملکرد پرسنل',
    meetingDate: '۱۴۰۳/۰۴/۲۸',
    secretary: 'زهرا نوری',
    chair: 'رئیس منابع انسانی',
    status: 'draft',
    confidentiality: 'restricted',
    decisionCount: 2,
    lastModified: '۱۴۰۳/۰۴/۲۹',
    version: '۰.۳',
    orgUnit: 'منابع انسانی',
  },
  {
    id: 'm5',
    meetingTitle: 'جلسه بررسی قراردادهای جدید',
    meetingDate: '۱۴۰۳/۰۴/۲۰',
    secretary: 'رضا موسوی',
    chair: 'معاون حقوقی',
    status: 'rejected',
    confidentiality: 'confidential',
    decisionCount: 1,
    lastModified: '۱۴۰۳/۰۴/۲۲',
    version: '۰.۵',
    orgUnit: 'امور حقوقی',
  },
];

export const MOCK_INTERNAL_PARTICIPANTS: InternalParticipant[] = [
  {
    id: 'p1',
    name: 'دکتر حسینی',
    position: 'رئیس هیئت مدیره',
    orgUnit: 'هیئت مدیره',
    invitationStatus: 'accepted',
    attendanceStatus: 'present',
  },
  {
    id: 'p2',
    name: 'مهندس رضایی',
    position: 'مدیر فناوری اطلاعات',
    orgUnit: 'اداره فناوری اطلاعات',
    invitationStatus: 'accepted',
    attendanceStatus: 'present',
  },
  {
    id: 'p3',
    name: 'علی محمدی',
    position: 'کارشناس ارشد',
    orgUnit: 'معاونت برنامه‌ریزی',
    invitationStatus: 'accepted',
    attendanceStatus: 'online',
  },
  {
    id: 'p4',
    name: 'سارا کریمی',
    position: 'مدیر پروژه',
    orgUnit: 'اداره فناوری اطلاعات',
    invitationStatus: 'declined',
    attendanceStatus: 'absent',
    notes: 'سفر اداری',
  },
];

export const MOCK_EXTERNAL_PARTICIPANTS: ExternalParticipant[] = [
  {
    id: 'ep1',
    fullName: 'احمد صادقی',
    organization: 'شرکت مشاوران فناوری',
    position: 'مدیرعامل',
    mobile: '09121234567',
    email: 'ahmad@techconsult.ir',
    attendanceStatus: 'present',
  },
];

export const MOCK_AGENDA_ITEMS: AgendaItem[] = [
  {
    id: 'a1',
    order: 1,
    title: 'بررسی عملکرد سه‌ماهه اول',
    description: 'ارزیابی شاخص‌های کلیدی عملکرد در سه‌ماهه اول سال جاری',
    presenter: 'مهندس رضایی',
    allocatedTime: 30,
    discussionResult: 'عملکرد واحدها مطلوب ارزیابی شد و پیشنهادهای بهبود ارائه گردید',
    resultType: 'discussion',
  },
  {
    id: 'a2',
    order: 2,
    title: 'تصویب برنامه عملیاتی نیمه دوم',
    description: 'بررسی و تصویب برنامه عملیاتی واحدها برای نیمه دوم سال',
    presenter: 'علی محمدی',
    allocatedTime: 45,
    discussionResult: 'برنامه پیشنهادی با اصلاحات جزئی تصویب شد',
    resultType: 'resolution',
  },
  {
    id: 'a3',
    order: 3,
    title: 'تخصیص منابع پروژه سامانه مدیریت',
    description: 'تعیین منابع انسانی و مالی موردنیاز برای پروژه',
    presenter: 'سارا کریمی',
    allocatedTime: 20,
    discussionResult: 'نیازمند هماهنگی بیشتر با معاونت مالی',
    resultType: 'deferred',
  },
];

// Still used by MinutesDashboardPage and MinutesMeetingReportPage (out of scope).
export const MOCK_DECISIONS: DecisionSummary[] = [
  {
    id: 'd1',
    title: 'استقرار سامانه مدیریت پروژه',
    description: 'نصب و راه‌اندازی سامانه مدیریت پروژه جدید تا پایان ماه جاری',
    agendaItemId: 'a2',
    priority: 'urgent',
    status: 'in_progress',
    primaryOwner: 'مهندس رضایی',
    collaborators: ['علی محمدی', 'سارا کریمی'],
    proposedBy: 'دکتر حسینی',
    responsibleUnit: 'اداره فناوری اطلاعات',
    startDate: '۱۴۰۳/۰۵/۱۵',
    deadline: '۱۴۰۳/۰۵/۳۱',
    progressPercent: 60,
    requiresFollowup: true,
    confidentiality: 'organizational',
  },
  {
    id: 'd2',
    title: 'تهیه گزارش مالی فصل دوم',
    description: 'تهیه و ارائه گزارش جامع مالی فصل دوم به هیئت مدیره',
    priority: 'important',
    status: 'planned',
    primaryOwner: 'محمد احمدی',
    collaborators: ['زهرا نوری'],
    responsibleUnit: 'اداره مالی',
    startDate: '۱۴۰۳/۰۵/۲۰',
    deadline: '۱۴۰۳/۰۶/۱۰',
    progressPercent: 0,
    requiresFollowup: true,
    confidentiality: 'confidential',
  },
  {
    id: 'd3',
    title: 'برگزاری دوره آموزشی کارکنان',
    description: 'برنامه‌ریزی و اجرای دوره آموزشی مهارت‌های نرم برای کارکنان',
    priority: 'normal',
    status: 'waiting_coordination',
    primaryOwner: 'زهرا نوری',
    collaborators: [],
    responsibleUnit: 'منابع انسانی',
    deadline: '۱۴۰۳/۰۶/۳۰',
    progressPercent: 20,
    requiresFollowup: false,
    confidentiality: 'organizational',
  },
  {
    id: 'd4',
    title: 'بازبینی آیین‌نامه داخلی',
    description: 'بازبینی و به‌روزرسانی آیین‌نامه داخلی سازمان',
    priority: 'low',
    status: 'completed',
    primaryOwner: 'رضا موسوی',
    collaborators: ['محمد احمدی'],
    responsibleUnit: 'امور حقوقی',
    deadline: '۱۴۰۳/۰۵/۱۰',
    progressPercent: 100,
    requiresFollowup: false,
    confidentiality: 'organizational',
  },
  {
    id: 'd5',
    title: 'ارتقاء امنیت شبکه',
    description: 'پیاده‌سازی پروتکل‌های امنیتی جدید در زیرساخت شبکه',
    priority: 'urgent',
    status: 'in_progress',
    primaryOwner: 'مهندس رضایی',
    collaborators: ['علی محمدی'],
    responsibleUnit: 'اداره فناوری اطلاعات',
    startDate: '۱۴۰۳/۰۴/۰۱',
    deadline: '۱۴۰۳/۰۵/۱۵',
    progressPercent: 45,
    requiresFollowup: true,
    confidentiality: 'restricted',
    notes: 'پیشرفت کمتر از برنامه — نیاز به بررسی موانع',
  },
];

export const MOCK_APPROVALS: ApprovalSummary[] = [
  {
    id: 'ap1',
    approverName: 'دکتر حسینی',
    position: 'رئیس هیئت مدیره',
    unit: 'هیئت مدیره',
    approvalOrder: 1,
    method: 'digital',
    status: 'approved',
  },
  {
    id: 'ap2',
    approverName: 'مهندس رضایی',
    position: 'مدیر فناوری اطلاعات',
    unit: 'اداره فناوری اطلاعات',
    approvalOrder: 2,
    method: 'digital',
    status: 'pending',
  },
  {
    id: 'ap3',
    approverName: 'زهرا نوری',
    position: 'رئیس منابع انسانی',
    unit: 'منابع انسانی',
    approvalOrder: 3,
    method: 'in_person',
    status: 'pending',
  },
];

export const MOCK_HISTORY: HistoryEvent[] = [
  {
    id: 'h1',
    actor: 'علی محمدی',
    action: 'صورت‌جلسه ایجاد شد',
    timestamp: '۱۴۰۳/۰۵/۱۲ ساعت ۱۴:۳۰',
  },
  {
    id: 'h2',
    actor: 'علی محمدی',
    action: 'بخش شرکت‌کنندگان به‌روزرسانی شد',
    timestamp: '۱۴۰۳/۰۵/۱۳ ساعت ۰۹:۱۵',
  },
  {
    id: 'h3',
    actor: 'علی محمدی',
    action: 'برای تأیید ارسال شد',
    timestamp: '۱۴۰۳/۰۵/۱۴ ساعت ۱۱:۴۵',
  },
  {
    id: 'h4',
    actor: 'دکتر حسینی',
    action: 'صورت‌جلسه تأیید شد',
    timestamp: '۱۴۰۳/۰۵/۱۵ ساعت ۱۶:۰۰',
    notes: 'با اصلاح جزئی بند ۳ تأیید شد',
  },
];

export const MOCK_DASHBOARD_STATS = {
  draftMinutes: 2,
  pendingMyApproval: 1,
  activeDecisions: 3,
  overdueDecisions: 1,
  nearDeadlineDecisions: 2,
  completedDecisions: 4,
};
