port: 7880
log_level: info

rtc:
  tcp_port: 7881
  port_range_start: 50000
  port_range_end: 60000
  use_external_ip: true

redis:
  address: ${LIVEKIT_REDIS_ADDRESS}

keys:
  ${LIVEKIT_API_KEY}: ${LIVEKIT_API_SECRET}

prometheus_port: 6789

turn:
  enabled: true
  domain: ${LIVEKIT_TURN_DOMAIN}
  udp_port: 3478
  tls_port: 5349

webhook:
  api_key: ${LIVEKIT_API_KEY}
  urls:
    - ${LIVEKIT_WEBHOOK_URL}

room:
  auto_create: false
  empty_timeout: 300
  departure_timeout: 60
  max_participants: 20
